### ISSUE TITLE
Can't install on PHP 7.x

### ISSUE THREAD

**Issue by tomomo** [kenjis/codeigniter-cli#20]
Hello.

`php cli ...` cannot be executed.

```bash
composer create-project kenjis/codeigniter-composer-installer example
cd $_
composer require kenjis/codeigniter-cli --dev
php vendor/kenjis/codeigniter-cli/install.php
php cli                                                                                                                                                                 ~/Workspace/example

PHP Fatal error:  Uncaught TypeError: Argument 4 passed to Aura\Project_Kernel\Project::__construct() must be of the type array, object given, called in /Users/teketeke/Workspace/example/vendor/aura/project-kernel/src/Factory.php on line 118 and defined in /Users/teketeke/Workspace/example/vendor/aura/project-kernel/src/Project.php:79
Stack trace:
#0 /Users/teketeke/Workspace/example/vendor/aura/project-kernel/src/Factory.php(118): Aura\Project_Kernel\Project->__construct()
#1 /Users/teketeke/Workspace/example/vendor/aura/project-kernel/src/Factory.php(82): Aura\Project_Kernel\Factory->newProject()
#2 /Users/teketeke/Workspace/example/vendor/aura/project-kernel/src/Factory.php(48): Aura\Project_Kernel\Factory->newContainer()
#3 /Users/teketeke/Workspace/example/cli(29): Aura\Project_Kernel\Factory->newKernel()
#4 {main}
  thrown in /Users/teketeke/Workspace/example/vendor/aura/project-kernel/src/Project.php on line 79
```

I think this is due to the change in `Aura`.
Will this package be unsupported?

## development
php 7.3, 7.4

**Comment by kenjis** [comment]
At the moment, this package does not work with Composer 2.0.
See <https://github.com/kenjis/codeigniter-tettei-apps#%E4%BE%9D%E5%AD%98%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB>.

> I think this is due to the change in Aura.

No. This is because Aura is out of dated.
To work with PHP 7.3 or 7.4, we need this PR https://github.com/auraphp/Aura.Cli_Kernel/pull/12

**Comment by tomomo** [comment]
Sorry for the delay in sending.

I Confirmed. It's the "composer" version.

I see...
It may be time to give up CI3 and move to CI4.

It was very useful. Thank you.

**Comment by kenjis** [comment]
Now we are updating Aura. See https://github.com/auraphp/Aura.Cli_Kernel/pull/13
